apiVersion: v1
kind: Secret
metadata:
  name: {{ include "module-service.dbSecretName" . }}
  labels:
    {{- include "module-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.database.url | quote }}
