apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: module-service-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nick-sohl/user-mgmt-ops.git
    targetRevision: main
    path: helm/module-service
    helm:
      releaseName: module-service-prod
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: module-service-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
